/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package opd;

import Extras.Validation;
import Extras.ViewDBRecords;

import java.awt.Component;
import java.awt.Container;
import java.awt.Dimension;
import java.awt.Toolkit;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import javax.swing.table.DefaultTableModel;
import net.sf.jasperreports.engine.JasperCompileManager;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.view.JasperViewer;

/**
 *
 * @author Sivakumar
 */
public class opdGUI extends javax.swing.JFrame {
    Connection conn = null;
    ResultSet rs,rs1 = null;
    PreparedStatement pst =null;
    Statement stmt = null;
    DefaultTableModel dm = null;
    int opdID = 1;
    int aa;
    
    private boolean phone = false;
    private boolean f_name = false;
    private boolean letter = false;
    private boolean number = false;

    /**
     * Creates new form OPD
     */
    public opdGUI() {
        initComponents();
        
        Dimension screenSize = Toolkit.getDefaultToolkit().getScreenSize();
        this.setSize(screenSize);
        
        lab_add_button.setEnabled(false);
        channel_add_button.setEnabled(false);
        
        jLabel23.setVisible(false);
        setEnableRec(channelpanel, false);
        setEnableRec(labpanel, false);
      
        conn = MySQLConn.ConnectDB();
        dm = (DefaultTableModel) TableAtMain.getModel();
        getopd();
        try {
        String SQL;
        SQL = "SELECT MAX(opdID) FROM opd";
        pst = conn.prepareStatement(SQL);
        rs1 = pst.executeQuery();
        while(rs1.next()) {
            opdID = 1+Integer.parseInt(rs1.getString(1));
            }
        
        opd_id.setText(String.valueOf(opdID));
        chnid.setText(String.valueOf(aa));
        labid.setText(String.valueOf(aa));
        } catch(Exception e) {
           JOptionPane.showMessageDialog(null,e);   
        }
        
        try {
            String SQL;
            SQL = "select DISTINCT field from physicians";
            pst = conn.prepareStatement(SQL);
            rs1 = pst.executeQuery();
            while(rs1.next()) {
                field_combo.addItem(rs1.getString(1));
                }
        } catch (SQLException ex) {
            Logger.getLogger(opdGUI.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        try {
            String SQL;
            SQL = "select DISTINCT ScanName from scantypedetails";
            pst = conn.prepareStatement(SQL);
            rs1 = pst.executeQuery();
            while(rs1.next()) {
                scan_combo.addItem(rs1.getString(1));
                }
        } catch (SQLException ex) {
            Logger.getLogger(opdGUI.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        try {
            String SQL;
            SQL = "select DISTINCT typeName from testcategorydetails";
            pst = conn.prepareStatement(SQL);
            rs1 = pst.executeQuery();
            while(rs1.next()) {
                test_combo.addItem(rs1.getString(1));
                }
        } catch (SQLException ex) {
            Logger.getLogger(opdGUI.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    /**
     * This method is called from within the constructor to initialise the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        Records_Button = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        channelpanel = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        field_combo = new javax.swing.JComboBox<>();
        physician_name_combo = new javax.swing.JComboBox<>();
        appointment_date = new com.toedter.calendar.JDateChooser();
        time_combo = new javax.swing.JComboBox<>();
        channel_add_button = new javax.swing.JButton();
        chnid = new javax.swing.JLabel();
        appointment_date_text = new javax.swing.JTextField();
        labpanel = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        test_combo = new javax.swing.JComboBox<>();
        scan_combo = new javax.swing.JComboBox<>();
        prescribed_by = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        reasons_text = new javax.swing.JTextArea();
        lab_add_button = new javax.swing.JButton();
        labid = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jLabel15 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        opdid_text = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        diagnoses_text = new javax.swing.JTextArea();
        consult_add_button = new javax.swing.JButton();
        jScrollPane5 = new javax.swing.JScrollPane();
        prescribed_medicines = new javax.swing.JTextArea();
        doc_text = new javax.swing.JTextField();
        opd_add_button = new javax.swing.JButton();
        jPanel6 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        visit_type_combo = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        age_text = new javax.swing.JTextField();
        payment_text = new javax.swing.JTextField();
        jLabel24 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        first_name = new javax.swing.JTextField();
        last_name = new javax.swing.JTextField();
        contact = new javax.swing.JTextField();
        title_combo = new javax.swing.JComboBox<>();
        jLabel7 = new javax.swing.JLabel();
        opd_id = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        TableAtMain = new javax.swing.JTable();
        jPanel7 = new javax.swing.JPanel();
        jLabel26 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        jTextField12 = new javax.swing.JTextField();
        jTextField13 = new javax.swing.JTextField();
        jTextField14 = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED), "", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 11), new java.awt.Color(0, 102, 102))); // NOI18N

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel4.setText("OPD Patient Panel");

        Records_Button.setText("Records");
        Records_Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Records_ButtonActionPerformed(evt);
            }
        });

        jButton1.setText("Back");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Report");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 438, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton2)
                .addGap(48, 48, 48)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(Records_Button, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(55, 55, 55))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(Records_Button, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton1)
                        .addComponent(jButton2)))
                .addContainerGap())
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED), "Patient Details"));

        channelpanel.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED), "Channeling Details"));

        jLabel9.setText("OPD ID");

        jLabel10.setText("Field");

        jLabel11.setText("Physician Name");

        jLabel12.setText("Appointment Date");

        jLabel13.setText("Time");

        field_combo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "select" }));
        field_combo.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                field_comboItemStateChanged(evt);
            }
        });
        field_combo.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                field_comboFocusLost(evt);
            }
        });

        physician_name_combo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "select" }));
        physician_name_combo.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                physician_name_comboFocusGained(evt);
            }
        });

        appointment_date.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                appointment_datePropertyChange(evt);
            }
        });

        time_combo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "select", "1:00", "2:00", "3:00", "4:00", "5:00", "6:00", "7:00", "8:00", "9:00", "10:00", "11:00", "12:00" }));

        channel_add_button.setText("Add");
        channel_add_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                channel_add_buttonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout channelpanelLayout = new javax.swing.GroupLayout(channelpanel);
        channelpanel.setLayout(channelpanelLayout);
        channelpanelLayout.setHorizontalGroup(
            channelpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(channelpanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(channelpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel9)
                    .addComponent(jLabel10)
                    .addComponent(jLabel11)
                    .addComponent(jLabel12)
                    .addComponent(jLabel13))
                .addGap(44, 44, 44)
                .addGroup(channelpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(field_combo, 0, 151, Short.MAX_VALUE)
                    .addComponent(physician_name_combo, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(time_combo, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(chnid, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, channelpanelLayout.createSequentialGroup()
                        .addComponent(appointment_date_text)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(appointment_date, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, channelpanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(channel_add_button, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30))
        );
        channelpanelLayout.setVerticalGroup(
            channelpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(channelpanelLayout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(channelpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel9)
                    .addComponent(chnid, javax.swing.GroupLayout.DEFAULT_SIZE, 21, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(channelpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(field_combo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(channelpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(physician_name_combo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(channelpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel12)
                    .addComponent(appointment_date, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(appointment_date_text, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(channelpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel13)
                    .addComponent(time_combo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(channel_add_button, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(60, Short.MAX_VALUE))
        );

        labpanel.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED), "Lab Visit"));

        jLabel14.setText("OPD ID");

        jLabel16.setText("Test");

        jLabel17.setText("Scan");

        jLabel18.setText("Prescribed by");

        jLabel19.setText("Reasons");

        test_combo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "select" }));

        scan_combo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "select" }));

        reasons_text.setColumns(20);
        reasons_text.setRows(5);
        jScrollPane1.setViewportView(reasons_text);

        lab_add_button.setText("Add");
        lab_add_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lab_add_buttonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout labpanelLayout = new javax.swing.GroupLayout(labpanel);
        labpanel.setLayout(labpanelLayout);
        labpanelLayout.setHorizontalGroup(
            labpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, labpanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(labpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel14)
                    .addComponent(jLabel16)
                    .addComponent(jLabel17)
                    .addComponent(jLabel18)
                    .addComponent(jLabel19))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(labpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 174, Short.MAX_VALUE)
                    .addComponent(labid, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(scan_combo, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(test_combo, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(prescribed_by)
                    .addGroup(labpanelLayout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addComponent(lab_add_button, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(32, 32, 32))
        );
        labpanelLayout.setVerticalGroup(
            labpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(labpanelLayout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(labpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel14)
                    .addComponent(labid, javax.swing.GroupLayout.DEFAULT_SIZE, 21, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(labpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel16)
                    .addComponent(test_combo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(labpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel17)
                    .addComponent(scan_combo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(labpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel18)
                    .addComponent(prescribed_by, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(labpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(labpanelLayout.createSequentialGroup()
                        .addGap(52, 52, 52)
                        .addComponent(jLabel19))
                    .addGroup(labpanelLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lab_add_button, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(21, 21, 21))
        );

        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED), "Consultation Details"));

        jLabel15.setText("OPD ID");

        jLabel20.setText("Doctor Name");

        jLabel21.setText("Diagnoses");

        jLabel22.setText("Prescribed Medicines");

        diagnoses_text.setColumns(20);
        diagnoses_text.setRows(5);
        jScrollPane2.setViewportView(diagnoses_text);

        consult_add_button.setText("Add");
        consult_add_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                consult_add_buttonActionPerformed(evt);
            }
        });

        prescribed_medicines.setColumns(20);
        prescribed_medicines.setRows(5);
        jScrollPane5.setViewportView(prescribed_medicines);

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel15)
                    .addComponent(jLabel20)
                    .addComponent(jLabel21)
                    .addComponent(jLabel22))
                .addGap(38, 38, 38)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(opdid_text)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 146, Short.MAX_VALUE)
                    .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(doc_text)))
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(111, 111, 111)
                .addComponent(consult_add_button, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15)
                    .addComponent(opdid_text, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel20)
                    .addComponent(doc_text, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(53, 53, 53)
                        .addComponent(jLabel21)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 16, Short.MAX_VALUE)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                        .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(consult_add_button, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                        .addComponent(jLabel22)
                        .addGap(116, 116, 116))))
        );

        opd_add_button.setText("Add");
        opd_add_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                opd_add_buttonActionPerformed(evt);
            }
        });

        jPanel6.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel2.setText("First name");

        jLabel23.setForeground(new java.awt.Color(255, 0, 0));
        jLabel23.setText("Invalid");

        visit_type_combo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "select", "OPD", "Channeling", "Lab" }));
        visit_type_combo.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                visit_type_comboItemStateChanged(evt);
            }
        });

        jLabel6.setText("Contact No");

        age_text.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                age_textFocusLost(evt);
            }
        });
        age_text.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                age_textKeyPressed(evt);
            }
        });

        payment_text.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                payment_textFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                payment_textFocusLost(evt);
            }
        });
        payment_text.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                payment_textActionPerformed(evt);
            }
        });

        jLabel24.setText("OPD ID");

        jLabel1.setText("Title");

        jLabel5.setText("Age");

        jLabel8.setText("Payment");

        jLabel3.setText("Last name");

        first_name.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                first_nameFocusLost(evt);
            }
        });

        last_name.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                last_nameFocusLost(evt);
            }
        });

        contact.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                contactFocusLost(evt);
            }
        });

        title_combo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "select", "Mr", "Ms", "Mrs" }));

        jLabel7.setText("Visit type");

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                        .addGap(200, 200, 200)
                        .addComponent(jLabel23)
                        .addGap(32, 32, 32))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel7)
                                    .addComponent(jLabel8))
                                .addGap(44, 44, 44)
                                .addComponent(payment_text))
                            .addGroup(jPanel6Layout.createSequentialGroup()
                                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel1)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel6)
                                    .addComponent(jLabel24))
                                .addGap(34, 34, 34)
                                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(last_name)
                                    .addComponent(age_text)
                                    .addComponent(contact)
                                    .addComponent(first_name, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(visit_type_combo, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addGroup(jPanel6Layout.createSequentialGroup()
                                        .addComponent(title_combo, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(0, 0, Short.MAX_VALUE))
                                    .addComponent(opd_id, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))))
                .addContainerGap())
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel24)
                    .addComponent(opd_id, javax.swing.GroupLayout.DEFAULT_SIZE, 21, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(title_combo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(first_name, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(last_name, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(age_text, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(contact, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel23)
                .addGap(6, 6, 6)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(visit_type_combo, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(16, 16, 16)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel8)
                    .addComponent(payment_text, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(20, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(130, 130, 130)
                        .addComponent(opd_add_button, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addComponent(channelpanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(labpanel, javax.swing.GroupLayout.PREFERRED_SIZE, 289, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(labpanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel5, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(channelpanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(opd_add_button, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );

        TableAtMain.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "opd ID", "Title", "First name", "Last name", "Age", "Contact No", "Visit Type", "Payment"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane4.setViewportView(TableAtMain);
        if (TableAtMain.getColumnModel().getColumnCount() > 0) {
            TableAtMain.getColumnModel().getColumn(0).setResizable(false);
            TableAtMain.getColumnModel().getColumn(1).setResizable(false);
            TableAtMain.getColumnModel().getColumn(2).setResizable(false);
            TableAtMain.getColumnModel().getColumn(3).setResizable(false);
            TableAtMain.getColumnModel().getColumn(4).setResizable(false);
            TableAtMain.getColumnModel().getColumn(5).setResizable(false);
            TableAtMain.getColumnModel().getColumn(6).setResizable(false);
            TableAtMain.getColumnModel().getColumn(7).setResizable(false);
        }

        jPanel7.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED), "Billing Details"));

        jLabel26.setText("OPD ID");

        jLabel27.setText("Total");

        jLabel28.setText("Balance");

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel26)
                    .addComponent(jLabel27)
                    .addComponent(jLabel28))
                .addGap(18, 18, 18)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTextField12, javax.swing.GroupLayout.DEFAULT_SIZE, 93, Short.MAX_VALUE)
                    .addComponent(jTextField13)
                    .addComponent(jTextField14))
                .addContainerGap())
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel26)
                    .addComponent(jTextField12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel27)
                    .addComponent(jTextField13, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel28)
                    .addComponent(jTextField14, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane4))
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addContainerGap(38, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void contactFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_contactFocusLost
        // TODO add your handling code here:
        phone = Validation.validatePhone(contact, jLabel23, phone);
    }//GEN-LAST:event_contactFocusLost

    private void channel_add_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_channel_add_buttonActionPerformed
        // TODO add your handling code here:
        String field = field_combo.getSelectedItem().toString();
        String phy_name = physician_name_combo.getSelectedItem().toString();
        String time = time_combo.getSelectedItem().toString();
       
        String app_date = appointment_date_text.getText();
 
        if (field.trim().equals("select") || phy_name.trim().equals("select") || app_date.trim().equals("") || time.trim().equals("select"))
            JOptionPane.showMessageDialog(null,"Fill All the Fields");
        else {
            try {
            pst = conn.prepareStatement("Insert into channeling values(?,?,?,?,?)");
            pst.setInt(1,opdID);
            pst.setString(2,String.valueOf(field));
            pst.setString(3,String.valueOf(phy_name));
            pst.setString(4,app_date);
            pst.setString(5,String.valueOf(time));
            pst.executeUpdate();
            JOptionPane.showMessageDialog(null,"Inserted Successfully");
            
            field_combo.setSelectedItem("select");
            physician_name_combo.setSelectedItem("select");
            appointment_date.setDate(null);
            time_combo.setSelectedItem("select");
           
        } catch (Exception e) {
          JOptionPane.showMessageDialog(null,e);
            }
        }
    }//GEN-LAST:event_channel_add_buttonActionPerformed

    private void lab_add_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lab_add_buttonActionPerformed
        // TODO add your handling code here:
        String test = test_combo.getSelectedItem().toString();
        String scan = scan_combo.getSelectedItem().toString();
        String pres_by = prescribed_by.getText();
        String reasons = reasons_text.getText();
       
        if(test.trim().equals("select") || scan.trim().equals("select") || pres_by.trim().equals("") || reasons.trim().equals(""))
            JOptionPane.showMessageDialog(null,"Fill All the Fields");
        else{
            try{
                pst = conn.prepareStatement("Insert into lab_visit values(?,?,?,?,?)");
                pst.setInt(1,opdID);
                pst.setString(2,String.valueOf(test));
                pst.setString(3,String.valueOf(scan));
                pst.setString(4,pres_by);
                pst.setString(5,reasons);
                pst.executeUpdate();
                JOptionPane.showMessageDialog(null,"Inserted Successfully");
                
                test_combo.setSelectedItem("select");
                scan_combo.setSelectedItem("select");
                prescribed_by.setText(null);
                reasons_text.setText(null);
               
            } catch (SQLException ex) {
                Logger.getLogger(opdGUI.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_lab_add_buttonActionPerformed

    private void consult_add_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_consult_add_buttonActionPerformed
        // TODO add your handling code here:
        String opdid = opdid_text.getText();
        String doc_name = doc_text.getText();
        String diagnoses = diagnoses_text.getText();
        String pres_medicines = prescribed_medicines.getText();
       
        if(opdid.trim().equals("") || doc_name.trim().equals("") || diagnoses.trim().equals("") || pres_medicines.trim().equals(""))
            JOptionPane.showMessageDialog(null,"Fill All the Fields");
        else{
             try{
                pst = conn.prepareStatement("Insert into consult_details values(?,?,?,?)");
                pst.setString(1,opdid);
                pst.setString(2,String.valueOf(doc_name));
                pst.setString(3,diagnoses);
                pst.setString(4,pres_medicines);
                pst.executeUpdate();
                JOptionPane.showMessageDialog(null,"Inserted Successfully");
                
                opdid_text.setText(null);
                doc_text.setText(null);
                diagnoses_text.setText(null);
                prescribed_medicines.setText(null);        
                
            } catch (SQLException ex) {
                Logger.getLogger(opdGUI.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_consult_add_buttonActionPerformed

    private void payment_textActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_payment_textActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_payment_textActionPerformed

    private void opd_add_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_opd_add_buttonActionPerformed
        // TODO add your handling code here:
        String title = title_combo.getSelectedItem().toString();
        String fname = first_name.getText();
        String lname = last_name.getText();
        String age = age_text.getText();
        String contact_no = contact.getText();
        String visit_type = visit_type_combo.getSelectedItem().toString();
        String payment = payment_text.getText();
        
        if(title.trim().equals("") || fname.trim().equals("") || lname.trim().equals("") || age.trim().equals("") ||
                contact_no.trim().equals("") || visit_type.trim().equals("select") || payment.trim().equals("") || phone == false)
        {
            JOptionPane.showMessageDialog(null,"Fill All the Fields");
        }
        else {
            try {
            pst = conn.prepareStatement("Insert into opd values(?,?,?,?,?,?,?,?)");
            pst.setInt(1,opdID);
            pst.setString(2,String.valueOf(title));
            pst.setString(3,fname);
            pst.setString(4,lname);
            pst.setString(5,age);
            pst.setString(6,contact_no);
            pst.setString(7,String.valueOf(visit_type));
            pst.setString(8,payment);
            pst.executeUpdate();
            JOptionPane.showMessageDialog(null,"Inserted Successfully");
            
           dm.addRow(new Object[]{String.valueOf(opdID),title,fname,lname,age,contact_no,visit_type,payment});
           ++opdID;
           
            title_combo.setSelectedItem("select");
            first_name.setText(null);
            last_name.setText(null);
            age_text.setText(null);
            contact.setText(null);
//            visit_type_combo.setSelectedItem("select");
            payment_text.setText(null);
           
        } catch (Exception e) {
          JOptionPane.showMessageDialog(null,e);
            }
        }
    }//GEN-LAST:event_opd_add_buttonActionPerformed

    private void visit_type_comboItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_visit_type_comboItemStateChanged
        // TODO add your handling code here:
        String get_type = visit_type_combo.getSelectedItem().toString();
        if (get_type.equals("Channeling"))
        {
            setEnableRec(channelpanel, true);
            setEnableRec(labpanel, false);
            chnid.setText(String.valueOf(opdID));
            
            String SQL;
            SQL = "SELECT MAX(opdID) FROM opd ";
            try 
            {
                pst = conn.prepareStatement(SQL);
                rs1 = pst.executeQuery();
                aa = rs1.getInt(1);
                
                chnid.setText(String.valueOf(aa));  
                
            } catch (SQLException ex) {
                Logger.getLogger(opdGUI.class.getName()).log(Level.SEVERE, null, ex);
            } 
             getname();
        }
        else if(get_type.equals("Lab")) {
            setEnableRec(channelpanel, false);
            setEnableRec(labpanel, true);
            labid.setText(String.valueOf(opdID));
            
            String SQL;
            SQL = "SELECT MAX(opdID) FROM opd ";
            try 
            {
                pst = conn.prepareStatement(SQL);
                rs1 = pst.executeQuery();
                aa = rs1.getInt(1);
                
                labid.setText(String.valueOf(aa));  
                
            } catch (SQLException ex) {
                Logger.getLogger(opdGUI.class.getName()).log(Level.SEVERE, null, ex);
            }  
           
        } else {
            setEnableRec(channelpanel, false);
            setEnableRec(labpanel, false);
        }
       
    }//GEN-LAST:event_visit_type_comboItemStateChanged

    private void age_textKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_age_textKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_age_textKeyPressed

    private void Records_ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Records_ButtonActionPerformed
        // TODO add your handling code here:
        ViewDBRecords vr = new ViewDBRecords();
        vr.show();
    }//GEN-LAST:event_Records_ButtonActionPerformed

    private void first_nameFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_first_nameFocusLost
        // TODO add your handling code here:
        String s = first_name.getText();
        letter = Validation.checkLetter(s);
    }//GEN-LAST:event_first_nameFocusLost

    private void last_nameFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_last_nameFocusLost
        // TODO add your handling code here:
        String s = last_name.getText();
        letter = Validation.checkLetter(s);
    }//GEN-LAST:event_last_nameFocusLost

    private void age_textFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_age_textFocusLost
        // TODO add your handling code here:
        String s = age_text.getText();
        number = Validation.checkNumber(s);
    }//GEN-LAST:event_age_textFocusLost

    private void payment_textFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_payment_textFocusLost
        // TODO add your handling code here:
        String s = payment_text.getText();
        number = Validation.checkNumber(s);
    }//GEN-LAST:event_payment_textFocusLost

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
    
    }//GEN-LAST:event_jButton1ActionPerformed

    private void physician_name_comboFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_physician_name_comboFocusGained
        // TODO add your handling code here:    
        //getname();
    }//GEN-LAST:event_physician_name_comboFocusGained

    private void appointment_datePropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_appointment_datePropertyChange
        // TODO add your handling code here:
        appointment_date_text.setText(((JTextField)appointment_date.getDateEditor().getUiComponent()).getText());
    }//GEN-LAST:event_appointment_datePropertyChange

    private void payment_textFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_payment_textFocusGained
        // TODO add your handling code here:
        getPayment();
    }//GEN-LAST:event_payment_textFocusGained

    private void field_comboFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_field_comboFocusLost
        // TODO add your handling code here:
        getname();
    }//GEN-LAST:event_field_comboFocusLost

    private void field_comboItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_field_comboItemStateChanged
        // TODO add your handling code here:
//        getname();
    }//GEN-LAST:event_field_comboItemStateChanged

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
          try{
           String report="C:\\Users\\Haran\\Documents\\NetBeansProjects\\ps_Atlanta\\src\\OPD_report\\OPD_report.jrxml";
           JasperReport jasp=JasperCompileManager.compileReport(report);
           JasperPrint jas_print=JasperFillManager.fillReport(jasp,null,conn);
           JasperViewer.viewReport(jas_print);
       }
       catch(Exception e){
          JOptionPane.showMessageDialog(null, e);
       }
    }//GEN-LAST:event_jButton2ActionPerformed
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(opdGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(opdGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(opdGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(opdGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new opdGUI().setVisible(true);
            }
        });
    }
    
    public void getname(){
    String fc = field_combo.getSelectedItem().toString();
        try {
            
            String SQL;
            SQL = "select lname from physicians WHERE field = '"+fc+"'";
            pst = conn.prepareStatement(SQL);
            rs1 = pst.executeQuery();
            while(rs1.next()) {
                physician_name_combo.addItem(rs1.getString(1));
                }
        } catch (SQLException ex) {
            Logger.getLogger(opdGUI.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    
    public void getPayment(){
      try {
            double docfee = 0;
            double scanfee = 0;
            double testfee = 0;
            double paymentTotal = 0;
            
            String phy_name = physician_name_combo.getSelectedItem().toString();
            String test = test_combo.getSelectedItem().toString();
            String scan = scan_combo.getSelectedItem().toString();
            
            String SQL = "select fee from physicians where lname like '"+phy_name+"'";
            pst = conn.prepareStatement(SQL);
            rs = pst.executeQuery();
            while(rs.next()) {
                docfee = Double.parseDouble(rs.getString(1));
            }
            
            String SQL1 = "select scanFee from scantypedetails where scanName like '"+scan+"'";
            pst = conn.prepareStatement(SQL1);
            rs = pst.executeQuery();
            while(rs.next()) {
                scanfee = Double.parseDouble(rs.getString(1));
            }
            
            String SQL2 = "select testFee from testcategorydetails where typeName like '"+test+"'";
            pst = conn.prepareStatement(SQL2);
            rs = pst.executeQuery();
            while(rs.next()) {
                testfee = Double.parseDouble(rs.getString(1));
            }
            
            paymentTotal = docfee+scanfee+testfee;
            payment_text.setText(String.valueOf(paymentTotal));
            
        } catch (SQLException ex) {
            Logger.getLogger(opdGUI.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    
    public void getopd() {
    while(dm.getRowCount() > 0)
    {
        dm.removeRow(0);
    }
    try {
        String SQL;
        SQL = "SELECT * FROM opd";
        PreparedStatement pst = conn.prepareStatement(SQL);
        rs = pst.executeQuery();
        while(rs.next())
        {
            opdID = 1+Integer.parseInt(rs.getString(1));
            dm.addRow(new Object[]{rs.getString(1),rs.getString(2),rs.getString(3),rs.getString(4),rs.getString(5),rs.getString(6),
                rs.getString(7),rs.getString(8)});
        }
    } catch(SQLException | NumberFormatException e) {
            JOptionPane.showMessageDialog(null,e);
    }
}
    
    // To hide the components in the panel
    private void setEnableRec(Component container, boolean enable){
    container.setEnabled(enable);

    try {
        Component[] components= ((Container) container).getComponents();
        for (int i = 0; i < components.length; i++) {
            setEnableRec(components[i], enable);
        }
    } catch (ClassCastException e) {

    }
}
 

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Records_Button;
    private javax.swing.JTable TableAtMain;
    private javax.swing.JTextField age_text;
    private com.toedter.calendar.JDateChooser appointment_date;
    private javax.swing.JTextField appointment_date_text;
    private javax.swing.JButton channel_add_button;
    private javax.swing.JPanel channelpanel;
    private javax.swing.JLabel chnid;
    private javax.swing.JButton consult_add_button;
    private javax.swing.JTextField contact;
    private javax.swing.JTextArea diagnoses_text;
    private javax.swing.JTextField doc_text;
    private javax.swing.JComboBox<String> field_combo;
    private javax.swing.JTextField first_name;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JTextField jTextField12;
    private javax.swing.JTextField jTextField13;
    private javax.swing.JTextField jTextField14;
    private javax.swing.JButton lab_add_button;
    private javax.swing.JLabel labid;
    private javax.swing.JPanel labpanel;
    private javax.swing.JTextField last_name;
    private javax.swing.JButton opd_add_button;
    private javax.swing.JLabel opd_id;
    private javax.swing.JTextField opdid_text;
    private javax.swing.JTextField payment_text;
    private javax.swing.JComboBox<String> physician_name_combo;
    private javax.swing.JTextField prescribed_by;
    private javax.swing.JTextArea prescribed_medicines;
    private javax.swing.JTextArea reasons_text;
    private javax.swing.JComboBox<String> scan_combo;
    private javax.swing.JComboBox<String> test_combo;
    private javax.swing.JComboBox<String> time_combo;
    private javax.swing.JComboBox<String> title_combo;
    private javax.swing.JComboBox<String> visit_type_combo;
    // End of variables declaration//GEN-END:variables
}
