/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package hrmanagement;

import Extras.Validation;

import database.DBConnection;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.text.SimpleDateFormat;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;
import net.proteanit.sql.DbUtils;

/**
 *
 * @author DELL
 */
public class Salary extends javax.swing.JFrame {

   // private static void setModel(TableModel resultSetToTableModel) {
      //  throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
   // }

    /**
     * Creates new form Salary
     */
    private  Connection con;
    private PreparedStatement ps;
    private ResultSet rs;
    private Statement st;
    private String idl;
    private boolean type,basic;
    private boolean isSearched=false;
    private DefaultTableModel model;
    private String utype;
    
    
       public void setType(String uType){
         this.utype=uType;
     }
    
    public Salary() {
        initComponents();
        bt_submit.setEnabled(false);
        s_basic.setText("");
        s_month.setText("");
       //  txt_medical.setText("");
       //  txt_meal.setText("");
        // txt_Travel.setText("");
         //txt_wel.setText("");
          txt_epf.setText("");
          btn_delete.setEnabled(false);
         txt_etf.setText("");
        // cm_month.setText("select");
         //txt_Atot.setText("");
        // txt_total.setText("");
         txt_net.setText("");
         
         
        
       try
        {
            con=DBConnection.ConnectionDB();
            //JOptionPane.showMessageDialog(null,"connected with "+con.toString());
        }
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(null,"not connect to server and message is"+e.getMessage());
        }
        
       
     
//        try
//        {
//            Statement stat = con.createStatement();
//            ResultSet res = stat.executeQuery("SELECT * FROM `salary`");
//            
//            Salary.setModel(DbUtils.resultSetToTableModel(res));
// 
//        }
//        catch(Exception ex)
//        {
//            JOptionPane.showMessageDialog(null, ex.getMessage());
//        }
//          
           String sql = "SELECT * FROM salary";
           try{
               st=con.createStatement();
               rs=st.executeQuery(sql);
               
              
           }
           catch(Exception e){
               JOptionPane.showMessageDialog(null, e);
           }
           finally{
               
             salary_table.setModel(DbUtils.resultSetToTableModel(rs));//show all employee details in a table
             model=(DefaultTableModel)salary_table.getModel();//currently add
           }
        
 
           
 
          
        
        
        
     
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        cm_month = new javax.swing.JComboBox<>();
        jLabel15 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel34 = new javax.swing.JLabel();
        jLabel35 = new javax.swing.JLabel();
        jLabel43 = new javax.swing.JLabel();
        bt_submit = new javax.swing.JButton();
        emp_idl = new javax.swing.JTextField();
        txt_basic = new javax.swing.JTextField();
        txt_over = new javax.swing.JTextField();
        txt_net = new javax.swing.JTextField();
        txt_epf = new javax.swing.JTextField();
        txt_etf = new javax.swing.JTextField();
        bt_search = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        la_namel = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        la_designationl = new javax.swing.JLabel();
        la_contactnumberl = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        la_emaill = new javax.swing.JLabel();
        s_basic = new javax.swing.JLabel();
        s_month = new javax.swing.JLabel();
        btn_delete = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        salary_table = new javax.swing.JTable();
        bt_edit = new javax.swing.JButton();
        bt_cancel = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jButton1.setText("Back");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Ebrima", 0, 14)); // NOI18N
        jLabel1.setText("Employee Id");

        jLabel13.setFont(new java.awt.Font("Ebrima", 0, 14)); // NOI18N
        jLabel13.setText("Month");

        cm_month.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select", "Jan", "Feb", "Mar", "Apr", "May", "June", "July", "Aug", "Sep", "Oct", "Nov", "Dec" }));

        jLabel15.setFont(new java.awt.Font("Ebrima", 0, 14)); // NOI18N
        jLabel15.setText("Basic Salary");

        jLabel21.setFont(new java.awt.Font("Ebrima", 0, 14)); // NOI18N
        jLabel21.setText("Over Time");

        jLabel34.setFont(new java.awt.Font("Ebrima", 0, 14)); // NOI18N
        jLabel34.setText("EPF");

        jLabel35.setFont(new java.awt.Font("Ebrima", 0, 14)); // NOI18N
        jLabel35.setText("ETF");

        jLabel43.setFont(new java.awt.Font("Ebrima", 1, 14)); // NOI18N
        jLabel43.setForeground(new java.awt.Color(255, 51, 51));
        jLabel43.setText("Net Salary");

        bt_submit.setFont(new java.awt.Font("Ebrima", 1, 18)); // NOI18N
        bt_submit.setText("Submit");
        bt_submit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_submitActionPerformed(evt);
            }
        });

        txt_basic.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_basicActionPerformed(evt);
            }
        });

        txt_etf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_etfActionPerformed(evt);
            }
        });

        bt_search.setText("Search");
        bt_search.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_searchActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Ebrima", 0, 14)); // NOI18N
        jLabel2.setText("Employee name");

        la_namel.setFont(new java.awt.Font("Ebrima", 0, 14)); // NOI18N
        la_namel.setText("Employee name");

        jLabel3.setFont(new java.awt.Font("Ebrima", 0, 14)); // NOI18N
        jLabel3.setText("Employee designation");

        jLabel4.setFont(new java.awt.Font("Ebrima", 0, 14)); // NOI18N
        jLabel4.setText("Employee ContactNumber");

        la_designationl.setFont(new java.awt.Font("Ebrima", 0, 14)); // NOI18N
        la_designationl.setText("Employee designation");

        la_contactnumberl.setFont(new java.awt.Font("Ebrima", 0, 14)); // NOI18N
        la_contactnumberl.setText("Employee ContactNumber");

        jLabel5.setFont(new java.awt.Font("Ebrima", 0, 14)); // NOI18N
        jLabel5.setText("Employee Email");

        la_emaill.setFont(new java.awt.Font("Ebrima", 0, 14)); // NOI18N
        la_emaill.setText("Employee Email");

        s_basic.setFont(new java.awt.Font("Ebrima", 0, 14)); // NOI18N
        s_basic.setForeground(new java.awt.Color(255, 51, 51));
        s_basic.setText("Error");

        s_month.setFont(new java.awt.Font("Ebrima", 0, 14)); // NOI18N
        s_month.setForeground(new java.awt.Color(255, 51, 51));
        s_month.setText("Error");

        btn_delete.setFont(new java.awt.Font("Ebrima", 1, 18)); // NOI18N
        btn_delete.setText("Delete");
        btn_delete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_deleteActionPerformed(evt);
            }
        });

        salary_table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        salary_table.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                salary_tableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(salary_table);

        bt_edit.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        bt_edit.setText("Edit");
        bt_edit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_editActionPerformed(evt);
            }
        });

        bt_cancel.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        bt_cancel.setText("Cancel");
        bt_cancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_cancelActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel34, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3)
                            .addComponent(jLabel2)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5)
                            .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel21, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel35, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel43, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(25, 25, 25)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(txt_basic, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(s_basic, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(cm_month, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(s_month, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txt_over, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(la_namel)
                                    .addComponent(la_designationl)
                                    .addComponent(la_emaill)
                                    .addComponent(la_contactnumberl)
                                    .addComponent(txt_epf, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txt_etf, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txt_net, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(emp_idl, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(55, 55, 55)
                                        .addComponent(bt_search)))
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addComponent(jButton1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 487, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(bt_submit, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btn_delete, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(34, 34, 34)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(bt_cancel)
                            .addComponent(bt_edit, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(23, 23, 23))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addComponent(jButton1)
                        .addGap(40, 40, 40)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(emp_idl, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(bt_search))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(28, 28, 28)
                                .addComponent(jLabel2))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(41, 41, 41)
                                .addComponent(la_namel)))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(la_designationl)
                            .addComponent(jLabel3))
                        .addGap(26, 26, 26)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(la_contactnumberl))
                        .addGap(30, 30, 30)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(la_emaill))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel15)
                            .addComponent(txt_basic, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(s_basic))
                        .addGap(21, 21, 21)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel13)
                            .addComponent(cm_month, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(s_month)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 396, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel21)
                    .addComponent(txt_over, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel34)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txt_epf, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(bt_submit)
                        .addComponent(bt_edit, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(70, 70, 70)
                        .addComponent(jLabel43))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btn_delete)
                            .addComponent(bt_cancel, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel35)
                            .addComponent(txt_etf, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(txt_net, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(123, Short.MAX_VALUE))
        );

        jPanel2.setBackground(new java.awt.Color(51, 153, 255));

        jLabel12.setFont(new java.awt.Font("Ebrima", 1, 24)); // NOI18N
        jLabel12.setText("Salary Details");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(369, 369, 369)
                .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(462, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jLabel12)
                .addContainerGap(19, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 982, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 10, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
    
        // TODO add your handling code here:  OverView ov =new OverView();
         this.setVisible(false);
        OverView view=new OverView();
        view.setType(utype);
        view.setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void bt_submitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_submitActionPerformed
        check();
        double basic;
        boolean output = false;
      try
        {
            basic=Integer.parseInt(txt_basic.getText());
            output=true;
        }
        catch(NumberFormatException ex)
        {
            s_basic.setText("Input basic amount");
            output=false;
        }
        if(cm_month.getSelectedIndex()<1 || txt_basic.getText().equals("") || output==false)
       {     
               if(cm_month.getSelectedIndex()<1)
                {
                 s_month.setText("Select the month");
                }
               else
                {
                s_month.setText("");
                }
           
                JOptionPane.showMessageDialog(null, "Input all values");
        
      }
        else
          {        
        double tot=0;
        double epf=0;
        double etf=0;
        double ov=900;
        
        
        
       
        
        
        basic=Integer.parseInt(txt_basic.getText());
        epf=((12.00/100.00)*basic);
         txt_epf.setText(""+epf);
        etf=((3.00/100.00)*basic);
         txt_etf.setText(""+etf);
         
        
    
        
        
        
        tot=((basic+ov)-((etf+epf)));
        
        
        txt_net.setText(""+tot);
        
        String sql="insert into salary(Emp_id,Month,BasicSalary,NetSalary) values(?,?,?,?)";
        
        
            try {
                ps=con.prepareStatement(sql);
                ps.setString(1,emp_idl.getText());
                ps.setString(2, cm_month.getSelectedItem().toString());
                ps.setString(3, txt_basic.getText());
                ps.setString(4,txt_net.getText());
                
                int rowAffected=ps.executeUpdate();
                if(rowAffected > 0){
                    JOptionPane.showMessageDialog(null,"All informations are validated");
                    
                }
                else{
                     JOptionPane.showMessageDialog(null,"cannot added");
                }
            } catch (SQLException ex) {
                Logger.getLogger(Salary.class.getName()).log(Level.SEVERE, null, ex);
            }
            finally{
            try {
                ps.close();
            } catch (SQLException ex) {
                Logger.getLogger(Salary.class.getName()).log(Level.SEVERE, null, ex);
            }
            }
              JOptionPane.showMessageDialog(null,"" +"Successfuly added");
                emp_idl.setText("");
                la_namel.setText("");
                la_designationl.setText("");
                la_contactnumberl.setText("");
                la_emaill.setText("");
                txt_basic.setText("");
                txt_epf.setText("");
                txt_etf.setText("");
                txt_net.setText("");
                txt_over.setText("");
                cm_month.setSelectedIndex(0);
         
          }
        
        
           String sql = "SELECT * FROM salary";
           try{
               st=con.createStatement();
               rs=st.executeQuery(sql);   
                salary_table.setModel(DbUtils.resultSetToTableModel(rs));//show all employee details in a table
             model=(DefaultTableModel)salary_table.getModel();//currently add
           }
           catch(Exception e){
               JOptionPane.showMessageDialog(null, e);
           }
           finally{
            try {
                st.close();
                 rs.close();
            } catch (SQLException ex) {
                Logger.getLogger(Salary.class.getName()).log(Level.SEVERE, null, ex);
            }
              
            
           }
        
        
    }//GEN-LAST:event_bt_submitActionPerformed

    private void txt_basicActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_basicActionPerformed
       
    }//GEN-LAST:event_txt_basicActionPerformed

    private void bt_searchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_searchActionPerformed
        // TODO add your handling code here:
        
        String id=emp_idl.getText();
        if(emp_idl.getText().equals(""))
        {
            JOptionPane.showMessageDialog(null, "Input some value");
        }
        else
        {
            String sql1 = "SELECT * FROM employee where `idEmployee`='"+emp_idl.getText()+"'";
            try
            {

                 st = con.createStatement();
                  rs = st.executeQuery(sql1);

                //int count = 0;
                if ( rs.next())
                { 
                    la_namel.setText( rs.getString(2)+" "+ rs.getString(3));
                    la_designationl.setText( rs.getString(18));
                    la_contactnumberl.setText( rs.getString(8));
                    la_emaill.setText( rs.getString(9));
                   bt_submit.setEnabled(true);
                   isSearched=true;
                }   
                else
                {
                    bt_submit.setEnabled(false);
                    isSearched=false;
                    JOptionPane.showMessageDialog(null, "User Not found");
                }
            }
            catch(SQLException ex)
            {
                JOptionPane.showMessageDialog(null, ex.getMessage());
                isSearched=false;
            }
            finally{
                try {
                    st.close();
                      rs.close();
                } catch (SQLException ex) {
                    Logger.getLogger(Salary.class.getName()).log(Level.SEVERE, null, ex);
                }
              
            }
            
            try{
                double value=0;
                String value1="";
                String sql="SELECT * from othours where empidot='"+emp_idl.getText()+"'";
                st=con.createStatement();

                rs=st.executeQuery(sql);

                while(rs.next()){
                value +=Double.parseDouble(rs.getString("total"));

                }
               txt_over.setText(String.valueOf(value));
            
            }
            catch(Exception e){
                JOptionPane.showMessageDialog(null, e);
            }
            finally{
                try {
                    st.close();
                    rs.close();
                } catch (SQLException ex) {
                    Logger.getLogger(Salary.class.getName()).log(Level.SEVERE, null, ex);
                }

            }
        
        }
                    
        
    }//GEN-LAST:event_bt_searchActionPerformed

    private void txt_etfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_etfActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_etfActionPerformed

    private void salary_tableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_salary_tableMouseClicked
        
        if(!bt_edit.isEnabled()){
            emp_idl.setText(String.valueOf(model.getValueAt(salary_table.getSelectedRow(),1)));
            txt_basic.setText(String.valueOf(model.getValueAt(salary_table.getSelectedRow(),3)));
            txt_net.setText(String.valueOf(model.getValueAt(salary_table.getSelectedRow(),4)));
            btn_delete.setEnabled(true);
        }
        else{
            JOptionPane.showMessageDialog(null, "click edit button for configuration");
             btn_delete.setEnabled(false);
        }
    }//GEN-LAST:event_salary_tableMouseClicked

    private void bt_editActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_editActionPerformed
        bt_edit.setEnabled(false);
        bt_cancel.setEnabled(true);
        bt_search.setEnabled(false);
        bt_submit.setEnabled(false);
    }//GEN-LAST:event_bt_editActionPerformed

    private void bt_cancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_cancelActionPerformed
        bt_edit.setEnabled(true);
        bt_cancel.setEnabled(false);
        bt_search.setEnabled(true);
        emp_idl.setText("");
        txt_basic.setText("");
        txt_net.setText("");
        txt_over.setText("");
        s_basic.setText("");
        s_month.setText("");
        bt_submit.setEnabled(false);
        cm_month.setSelectedIndex(0);
        btn_delete.setEnabled(false);
    }//GEN-LAST:event_bt_cancelActionPerformed

    private void btn_deleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_deleteActionPerformed
         int i=salary_table.getSelectedRow();
        String x=model.getValueAt(i, 0).toString();
        try{
            ps=con.prepareStatement("DELETE from salary where Id LIKE ?");
            ps.setString(1, x);
            ps.execute();
            JOptionPane.showMessageDialog(null,"Deleted successfuly!");
        }
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(null,e);
        }
        finally{
             try {
                 ps.close();
             } catch (SQLException ex) {
                 Logger.getLogger(Salary.class.getName()).log(Level.SEVERE, null, ex);
             }
        }
        
         String sql = "SELECT * FROM salary";
           try{
               st=con.createStatement();
               rs=st.executeQuery(sql);   
                salary_table.setModel(DbUtils.resultSetToTableModel(rs));//show all employee details in a table
             model=(DefaultTableModel)salary_table.getModel();//currently add
           }
           catch(Exception e){
               JOptionPane.showMessageDialog(null, e);
           }
           finally{
            try {
                st.close();
                 rs.close();
            } catch (SQLException ex) {
                Logger.getLogger(Salary.class.getName()).log(Level.SEVERE, null, ex);
            }
              
            
           }
        
    }//GEN-LAST:event_btn_deleteActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Salary.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Salary.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Salary.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Salary.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Salary().setVisible(true);
            }
        });
    }
    
    public void check()
    {
        if(cm_month.getSelectedIndex()<1)
        {
            type=false;
            s_month.setText("Select a month");
        }
        else
        {
            type=true;
            s_month.setText("");
        }
        
        if(txt_basic.getText().equals(""))
        {
            s_basic.setText("Input your basic salary");
            basic=false;
        }
        else
        {
            basic =true;
            s_basic.setText("");
        }
     
     }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bt_cancel;
    private javax.swing.JButton bt_edit;
    private javax.swing.JButton bt_search;
    private javax.swing.JButton bt_submit;
    private javax.swing.JButton btn_delete;
    private javax.swing.JComboBox<String> cm_month;
    private javax.swing.JTextField emp_idl;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel43;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel la_contactnumberl;
    private javax.swing.JLabel la_designationl;
    private javax.swing.JLabel la_emaill;
    private javax.swing.JLabel la_namel;
    private javax.swing.JLabel s_basic;
    private javax.swing.JLabel s_month;
    private javax.swing.JTable salary_table;
    private javax.swing.JTextField txt_basic;
    private javax.swing.JTextField txt_epf;
    private javax.swing.JTextField txt_etf;
    private javax.swing.JTextField txt_net;
    private javax.swing.JTextField txt_over;
    // End of variables declaration//GEN-END:variables
}
