package maternity;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */



import Home.Home_Main;
import java.awt.Dimension;
import java.awt.Toolkit;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.Calendar;
import java.util.HashMap;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import javax.swing.table.DefaultTableModel;
import net.sf.jasperreports.engine.JRException;
import net.sf.jasperreports.engine.JasperCompileManager;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.view.JasperViewer;
//import pms.opd.opdGUI;
import Pharmacy.Stock_management;
import opd.*;



/**
 *
 * @author Sivakumar
 */
public class MaternityGUI extends javax.swing.JFrame {
    
    Connection conn = null;
    ResultSet rs,rs1;
    PreparedStatement pst;
    Statement stmt;
    DefaultTableModel dm;
    int patientID = 1;
    /**
     * Creates new form Maternity
     */
    private boolean nic = false;
    private boolean phone_h = false;
    private boolean phone_m = false;
    private boolean phone = false;
    private boolean letter = false;
    private boolean number = false;
    
    public MaternityGUI() {
        initComponents();
        
        Dimension screenSize = Toolkit.getDefaultToolkit().getScreenSize();
        this.setSize(screenSize);
        
        jLabel31.setVisible(false);
        jLabel37.setVisible(false);
        jLabel38.setVisible(false);
        jLabel48.setVisible(false);
        jLabel49.setVisible(false);
        
        
        conn = maternity.MySQLConn.ConnectDB();
        dm = (DefaultTableModel) TableMat.getModel();
        
        maternity();
        
        try {
            String SQL;
            SQL = "SELECT MAX(patientID) FROM maternity";
            pst = conn.prepareStatement(SQL);
            rs1 = pst.executeQuery();
            while(rs1.next()) {
                patientID = 1+Integer.parseInt(rs1.getString(1));
            }
        
            maternity_ID.setText(String.valueOf(patientID));
            
        } catch(Exception e) {
           JOptionPane.showMessageDialog(null,e);   
        }
        
        try {
            String SQL;
            SQL = "select lname from physicians where field like 'Gynecology'";
            pst = conn.prepareStatement(SQL);
            rs1 = pst.executeQuery();
            while(rs1.next()) {
                mat_doc_combo.addItem(rs1.getString(1));
                }
        } catch (SQLException ex) {
            Logger.getLogger(opdGUI.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        try {
            String SQL;
            SQL = "select lname from physicians where field like 'Pediatrician'";
            pst = conn.prepareStatement(SQL);
            rs1 = pst.executeQuery();
            while(rs1.next()) {
                pediat_combo.addItem(rs1.getString(1));
                }
        } catch (SQLException ex) {
            Logger.getLogger(opdGUI.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }

    /**
     * This method is called from within the constructor to initialise the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel4 = new javax.swing.JPanel();
        jLayeredPane5 = new javax.swing.JLayeredPane();
        jLabel17 = new javax.swing.JLabel();
        search_maternity = new javax.swing.JTextField();
        jScrollPane3 = new javax.swing.JScrollPane();
        TableMat = new javax.swing.JTable();
        jLayeredPane6 = new javax.swing.JLayeredPane();
        jLabel18 = new javax.swing.JLabel();
        first_name = new javax.swing.JTextField();
        age_text = new javax.swing.JTextField();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        home_contact = new javax.swing.JTextField();
        jScrollPane4 = new javax.swing.JScrollPane();
        perm_add_text = new javax.swing.JTextArea();
        jLabel1 = new javax.swing.JLabel();
        last_name = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        title_combo = new javax.swing.JComboBox<String>();
        jLabel4 = new javax.swing.JLabel();
        mar_stat = new javax.swing.JComboBox<String>();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        res_add_text = new javax.swing.JTextArea();
        jLabel7 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        mobile_contact = new javax.swing.JTextField();
        dob_dc = new com.toedter.calendar.JDateChooser();
        jLabel30 = new javax.swing.JLabel();
        nic_text = new javax.swing.JTextField();
        jLabel31 = new javax.swing.JLabel();
        jLabel37 = new javax.swing.JLabel();
        jLabel38 = new javax.swing.JLabel();
        maternity_ID = new javax.swing.JLabel();
        dob_text_add = new javax.swing.JTextField();
        jLayeredPane1 = new javax.swing.JLayeredPane();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        mat_doc_combo = new javax.swing.JComboBox<String>();
        jLabel11 = new javax.swing.JLabel();
        fam_doc_text = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        pediat_combo = new javax.swing.JComboBox<String>();
        duedate_dc = new com.toedter.calendar.JDateChooser();
        duedate_text_add = new javax.swing.JTextField();
        jLayeredPane2 = new javax.swing.JLayeredPane();
        jLabel13 = new javax.swing.JLabel();
        nok_first_name = new javax.swing.JTextField();
        nok_title_com = new javax.swing.JComboBox<String>();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        nok_last_name = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        nok_relation = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        nok_add_text = new javax.swing.JTextArea();
        nok_contact_no = new javax.swing.JTextField();
        jLabel25 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        nok_nic_text = new javax.swing.JTextField();
        jLabel48 = new javax.swing.JLabel();
        jLabel49 = new javax.swing.JLabel();
        jLayeredPane3 = new javax.swing.JLayeredPane();
        jLabel26 = new javax.swing.JLabel();
        cat_combo = new javax.swing.JComboBox<String>();
        jLabel27 = new javax.swing.JLabel();
        jLabel45 = new javax.swing.JLabel();
        rate_text = new javax.swing.JTextField();
        roomno_combo = new javax.swing.JComboBox<String>();
        jPanel1 = new javax.swing.JPanel();
        register_button = new javax.swing.JButton();
        total_amount = new javax.swing.JTextField();
        jLabel46 = new javax.swing.JLabel();
        invoice_button = new javax.swing.JButton();
        clear_button = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel28 = new javax.swing.JLabel();
        jButton4 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel4.setBackground(new java.awt.Color(0, 102, 102));
        jPanel4.setOpaque(false);
        jPanel4.setPreferredSize(new java.awt.Dimension(1300, 700));

        jLayeredPane5.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel17.setText("Search");

        search_maternity.setPreferredSize(new java.awt.Dimension(300, 30));
        search_maternity.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                search_maternityKeyReleased(evt);
            }
        });

        javax.swing.GroupLayout jLayeredPane5Layout = new javax.swing.GroupLayout(jLayeredPane5);
        jLayeredPane5.setLayout(jLayeredPane5Layout);
        jLayeredPane5Layout.setHorizontalGroup(
            jLayeredPane5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jLayeredPane5Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(search_maternity, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(51, 51, 51))
        );
        jLayeredPane5Layout.setVerticalGroup(
            jLayeredPane5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jLayeredPane5Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jLayeredPane5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel17)
                    .addComponent(search_maternity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18))
        );
        jLayeredPane5.setLayer(jLabel17, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane5.setLayer(search_maternity, javax.swing.JLayeredPane.DEFAULT_LAYER);

        TableMat.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        TableMat.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Patient ID", "Title", "First Name", "Last Name", "Date of Birth", "Age", "NIC", "Address", "Contact No", "Room No"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        TableMat.setOpaque(false);
        TableMat.getTableHeader().setReorderingAllowed(false);
        jScrollPane3.setViewportView(TableMat);
        if (TableMat.getColumnModel().getColumnCount() > 0) {
            TableMat.getColumnModel().getColumn(0).setResizable(false);
            TableMat.getColumnModel().getColumn(1).setResizable(false);
            TableMat.getColumnModel().getColumn(2).setResizable(false);
            TableMat.getColumnModel().getColumn(3).setResizable(false);
            TableMat.getColumnModel().getColumn(4).setResizable(false);
            TableMat.getColumnModel().getColumn(5).setResizable(false);
            TableMat.getColumnModel().getColumn(6).setResizable(false);
            TableMat.getColumnModel().getColumn(7).setResizable(false);
            TableMat.getColumnModel().getColumn(8).setResizable(false);
            TableMat.getColumnModel().getColumn(9).setResizable(false);
        }

        jLayeredPane6.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED), "Personal Details", javax.swing.border.TitledBorder.LEFT, javax.swing.border.TitledBorder.DEFAULT_POSITION));

        jLabel18.setText("First name");

        first_name.setPreferredSize(new java.awt.Dimension(200, 30));
        first_name.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                first_nameFocusLost(evt);
            }
        });

        jLabel20.setText("Date of Birth");

        jLabel21.setText("Age");

        jLabel22.setText("Permanent");

        jLabel23.setText("Contact No");

        jLabel24.setText("Patient ID");

        home_contact.setPreferredSize(new java.awt.Dimension(200, 30));
        home_contact.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                home_contactFocusLost(evt);
            }
        });

        perm_add_text.setColumns(20);
        perm_add_text.setRows(5);
        jScrollPane4.setViewportView(perm_add_text);

        jLabel1.setText("Last name");

        last_name.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                last_nameFocusLost(evt);
            }
        });

        jLabel2.setText("Address");

        jLabel3.setText("Title");

        title_combo.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "select", "Mrs", "Ms" }));

        jLabel4.setText("Marital Status");

        mar_stat.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "select", "Married", "Single", "Unmarried" }));

        jLabel5.setText("Home");

        res_add_text.setColumns(20);
        res_add_text.setRows(5);
        jScrollPane1.setViewportView(res_add_text);

        jLabel7.setText("Address");

        jLabel6.setText("Residential");

        jLabel8.setText("Mobile");

        mobile_contact.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                mobile_contactFocusLost(evt);
            }
        });

        dob_dc.setDateFormatString("yyyy-MM-dd");
        dob_dc.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                dob_dcPropertyChange(evt);
            }
        });

        jLabel30.setText("NIC");

        nic_text.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                nic_textFocusLost(evt);
            }
        });

        jLabel31.setForeground(new java.awt.Color(255, 0, 0));
        jLabel31.setText("Invalid");

        jLabel37.setForeground(new java.awt.Color(255, 0, 0));
        jLabel37.setText("Invalid");

        jLabel38.setForeground(new java.awt.Color(255, 0, 0));
        jLabel38.setText("Invalid");

        dob_text_add.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                dob_text_addFocusLost(evt);
            }
        });

        javax.swing.GroupLayout jLayeredPane6Layout = new javax.swing.GroupLayout(jLayeredPane6);
        jLayeredPane6.setLayout(jLayeredPane6Layout);
        jLayeredPane6Layout.setHorizontalGroup(
            jLayeredPane6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jLayeredPane6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jLayeredPane6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jLayeredPane6Layout.createSequentialGroup()
                        .addGroup(jLayeredPane6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jLayeredPane6Layout.createSequentialGroup()
                                .addGroup(jLayeredPane6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jLayeredPane6Layout.createSequentialGroup()
                                        .addGap(0, 0, Short.MAX_VALUE)
                                        .addComponent(jLabel24)
                                        .addGap(33, 33, 33))
                                    .addGroup(jLayeredPane6Layout.createSequentialGroup()
                                        .addGroup(jLayeredPane6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel22)
                                            .addComponent(jLabel2))
                                        .addGap(0, 0, Short.MAX_VALUE)))
                                .addGap(4, 4, 4)
                                .addGroup(jLayeredPane6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 160, Short.MAX_VALUE)
                                    .addComponent(maternity_ID, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jLayeredPane6Layout.createSequentialGroup()
                                .addGroup(jLayeredPane6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel18)
                                    .addComponent(jLabel1))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(jLayeredPane6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(title_combo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(first_name, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(last_name, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(dob_text_add, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jLayeredPane6Layout.createSequentialGroup()
                                .addGroup(jLayeredPane6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jLayeredPane6Layout.createSequentialGroup()
                                        .addGroup(jLayeredPane6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel21)
                                            .addComponent(jLabel20))
                                        .addGap(0, 0, Short.MAX_VALUE))
                                    .addGroup(jLayeredPane6Layout.createSequentialGroup()
                                        .addComponent(jLabel30)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                                .addGroup(jLayeredPane6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(age_text, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(nic_text, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(dob_dc, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGroup(jLayeredPane6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jLayeredPane6Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel38)
                                .addGap(101, 101, 101))
                            .addGroup(jLayeredPane6Layout.createSequentialGroup()
                                .addGroup(jLayeredPane6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jLayeredPane6Layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGroup(jLayeredPane6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addGroup(jLayeredPane6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGroup(jLayeredPane6Layout.createSequentialGroup()
                                                    .addGroup(jLayeredPane6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(jLabel5)
                                                        .addComponent(jLabel8, javax.swing.GroupLayout.Alignment.TRAILING))
                                                    .addGap(54, 54, 54)
                                                    .addGroup(jLayeredPane6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                        .addComponent(home_contact, javax.swing.GroupLayout.PREFERRED_SIZE, 1, Short.MAX_VALUE)
                                                        .addComponent(mobile_contact, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                                .addComponent(jLabel23)
                                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jLayeredPane6Layout.createSequentialGroup()
                                                    .addComponent(jLabel37)
                                                    .addGap(38, 38, 38)))
                                            .addGroup(jLayeredPane6Layout.createSequentialGroup()
                                                .addGroup(jLayeredPane6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addGroup(jLayeredPane6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.TRAILING)
                                                        .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.TRAILING)))
                                                .addGroup(jLayeredPane6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(mar_stat, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                                    .addGroup(jLayeredPane6Layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jLabel31)))
                                .addContainerGap(20, Short.MAX_VALUE))))
                    .addGroup(jLayeredPane6Layout.createSequentialGroup()
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())))
        );
        jLayeredPane6Layout.setVerticalGroup(
            jLayeredPane6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jLayeredPane6Layout.createSequentialGroup()
                .addContainerGap(14, Short.MAX_VALUE)
                .addGroup(jLayeredPane6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(maternity_ID, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel24))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jLayeredPane6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(title_combo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jLayeredPane6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jLayeredPane6Layout.createSequentialGroup()
                        .addGroup(jLayeredPane6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(mar_stat, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jLayeredPane6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jLayeredPane6Layout.createSequentialGroup()
                                .addGap(29, 29, 29)
                                .addGroup(jLayeredPane6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel6)
                                    .addGroup(jLayeredPane6Layout.createSequentialGroup()
                                        .addGap(20, 20, 20)
                                        .addGroup(jLayeredPane6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel7)
                                            .addGroup(jLayeredPane6Layout.createSequentialGroup()
                                                .addGroup(jLayeredPane6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                    .addGroup(jLayeredPane6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                        .addComponent(jLabel20)
                                                        .addComponent(dob_text_add, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                    .addComponent(dob_dc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addGap(10, 10, 10)
                                                .addGroup(jLayeredPane6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                    .addComponent(age_text, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(jLabel21)))))))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jLayeredPane6Layout.createSequentialGroup()
                        .addGroup(jLayeredPane6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(first_name, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel18))
                        .addGap(18, 18, 18)
                        .addGroup(jLayeredPane6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(last_name, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1))))
                .addGap(24, 24, 24)
                .addGroup(jLayeredPane6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel30)
                    .addComponent(nic_text, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel31))
                .addGap(2, 2, 2)
                .addComponent(jLabel23, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jLayeredPane6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jLayeredPane6Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jLayeredPane6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(home_contact, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel37)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jLayeredPane6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(mobile_contact, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel8))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel38))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jLayeredPane6Layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addGroup(jLayeredPane6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jLayeredPane6Layout.createSequentialGroup()
                                .addGap(49, 49, 49)
                                .addComponent(jLabel22)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel2))
                            .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(25, 25, 25))))
        );
        jLayeredPane6.setLayer(jLabel18, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane6.setLayer(first_name, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane6.setLayer(age_text, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane6.setLayer(jLabel20, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane6.setLayer(jLabel21, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane6.setLayer(jLabel22, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane6.setLayer(jLabel23, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane6.setLayer(jLabel24, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane6.setLayer(home_contact, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane6.setLayer(jScrollPane4, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane6.setLayer(jLabel1, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane6.setLayer(last_name, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane6.setLayer(jLabel2, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane6.setLayer(jLabel3, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane6.setLayer(title_combo, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane6.setLayer(jLabel4, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane6.setLayer(mar_stat, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane6.setLayer(jLabel5, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane6.setLayer(jScrollPane1, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane6.setLayer(jLabel7, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane6.setLayer(jLabel6, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane6.setLayer(jLabel8, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane6.setLayer(mobile_contact, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane6.setLayer(dob_dc, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane6.setLayer(jLabel30, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane6.setLayer(nic_text, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane6.setLayer(jLabel31, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane6.setLayer(jLabel37, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane6.setLayer(jLabel38, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane6.setLayer(maternity_ID, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane6.setLayer(dob_text_add, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jLayeredPane1.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED), "Other Details"));

        jLabel9.setText("Due Date");

        jLabel10.setText("Maternity Doctor");

        mat_doc_combo.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "select" }));

        jLabel11.setText("Family Doctor");

        fam_doc_text.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                fam_doc_textFocusLost(evt);
            }
        });

        jLabel12.setText("Pediatrician");

        pediat_combo.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "select" }));

        duedate_dc.setDateFormatString("yyyy-MM-dd");
        duedate_dc.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                duedate_dcPropertyChange(evt);
            }
        });

        javax.swing.GroupLayout jLayeredPane1Layout = new javax.swing.GroupLayout(jLayeredPane1);
        jLayeredPane1.setLayout(jLayeredPane1Layout);
        jLayeredPane1Layout.setHorizontalGroup(
            jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jLayeredPane1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jLayeredPane1Layout.createSequentialGroup()
                        .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(fam_doc_text, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jLayeredPane1Layout.createSequentialGroup()
                                .addComponent(duedate_text_add)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(duedate_dc, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jLayeredPane1Layout.createSequentialGroup()
                        .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel10)
                            .addComponent(jLabel12))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(mat_doc_combo, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(pediat_combo, 0, 138, Short.MAX_VALUE))))
                .addContainerGap(22, Short.MAX_VALUE))
        );
        jLayeredPane1Layout.setVerticalGroup(
            jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jLayeredPane1Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel9)
                        .addComponent(duedate_text_add, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(duedate_dc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(fam_doc_text, javax.swing.GroupLayout.DEFAULT_SIZE, 32, Short.MAX_VALUE)
                    .addComponent(jLabel11))
                .addGap(18, 18, 18)
                .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(mat_doc_combo, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10))
                .addGap(18, 18, 18)
                .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(pediat_combo, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12)))
        );
        jLayeredPane1.setLayer(jLabel9, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(jLabel10, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(mat_doc_combo, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(jLabel11, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(fam_doc_text, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(jLabel12, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(pediat_combo, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(duedate_dc, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(duedate_text_add, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jLayeredPane2.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED), "Next of Kin Details"));

        jLabel13.setText("Title");

        nok_first_name.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                nok_first_nameFocusLost(evt);
            }
        });

        nok_title_com.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "select", "Mr", "Mrs", "Ms" }));

        jLabel14.setText("First name");

        jLabel15.setText("Last name");

        nok_last_name.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                nok_last_nameFocusLost(evt);
            }
        });

        jLabel16.setText("Relationship");

        nok_relation.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                nok_relationFocusLost(evt);
            }
        });

        jLabel19.setText("Address");

        nok_add_text.setColumns(20);
        nok_add_text.setRows(5);
        jScrollPane2.setViewportView(nok_add_text);

        nok_contact_no.setPreferredSize(new java.awt.Dimension(6, 25));
        nok_contact_no.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                nok_contact_noFocusLost(evt);
            }
        });

        jLabel25.setText("Contact No");

        jLabel29.setText("NIC");

        nok_nic_text.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                nok_nic_textFocusLost(evt);
            }
        });

        jLabel48.setForeground(new java.awt.Color(255, 0, 0));
        jLabel48.setText("Invalid");

        jLabel49.setForeground(new java.awt.Color(255, 0, 0));
        jLabel49.setText("Invalid");

        javax.swing.GroupLayout jLayeredPane2Layout = new javax.swing.GroupLayout(jLayeredPane2);
        jLayeredPane2.setLayout(jLayeredPane2Layout);
        jLayeredPane2Layout.setHorizontalGroup(
            jLayeredPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jLayeredPane2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jLayeredPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jLayeredPane2Layout.createSequentialGroup()
                        .addGroup(jLayeredPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel13)
                            .addComponent(jLabel14)
                            .addComponent(jLabel15)
                            .addComponent(jLabel29))
                        .addGap(38, 38, 38)
                        .addGroup(jLayeredPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(nok_title_com, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(nok_last_name)
                            .addComponent(nok_first_name)
                            .addComponent(nok_nic_text, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel48)
                        .addGap(105, 105, 105))
                    .addGroup(jLayeredPane2Layout.createSequentialGroup()
                        .addGroup(jLayeredPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel16)
                            .addComponent(jLabel19)
                            .addComponent(jLabel25))
                        .addGap(30, 30, 30)
                        .addGroup(jLayeredPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(nok_contact_no, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(nok_relation, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel49)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        jLayeredPane2Layout.setVerticalGroup(
            jLayeredPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jLayeredPane2Layout.createSequentialGroup()
                .addGroup(jLayeredPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nok_title_com, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel13))
                .addGap(18, 18, 18)
                .addGroup(jLayeredPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nok_first_name, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel14))
                .addGap(18, 18, 18)
                .addGroup(jLayeredPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nok_last_name, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel15))
                .addGap(18, 18, 18)
                .addGroup(jLayeredPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel29)
                    .addComponent(nok_nic_text, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel48))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jLayeredPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel16)
                    .addComponent(nok_relation, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jLayeredPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jLayeredPane2Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jLayeredPane2Layout.createSequentialGroup()
                        .addGap(50, 50, 50)
                        .addComponent(jLabel19)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jLayeredPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nok_contact_no, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel49)
                    .addComponent(jLabel25))
                .addContainerGap(22, Short.MAX_VALUE))
        );
        jLayeredPane2.setLayer(jLabel13, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane2.setLayer(nok_first_name, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane2.setLayer(nok_title_com, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane2.setLayer(jLabel14, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane2.setLayer(jLabel15, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane2.setLayer(nok_last_name, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane2.setLayer(jLabel16, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane2.setLayer(nok_relation, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane2.setLayer(jLabel19, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane2.setLayer(jScrollPane2, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane2.setLayer(nok_contact_no, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane2.setLayer(jLabel25, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane2.setLayer(jLabel29, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane2.setLayer(nok_nic_text, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane2.setLayer(jLabel48, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane2.setLayer(jLabel49, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jLayeredPane3.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED), "Room Details"));

        jLabel26.setText("Category");

        cat_combo.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "select", "Luxury", "Semi-Luxury", "Ordinary" }));

        jLabel27.setText("Room no");

        jLabel45.setText("Rate");

        rate_text.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                rate_textFocusLost(evt);
            }
        });

        roomno_combo.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "select" }));
        roomno_combo.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                roomno_comboFocusGained(evt);
            }
        });

        javax.swing.GroupLayout jLayeredPane3Layout = new javax.swing.GroupLayout(jLayeredPane3);
        jLayeredPane3.setLayout(jLayeredPane3Layout);
        jLayeredPane3Layout.setHorizontalGroup(
            jLayeredPane3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jLayeredPane3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jLayeredPane3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel26)
                    .addComponent(jLabel27)
                    .addComponent(jLabel45))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 42, Short.MAX_VALUE)
                .addGroup(jLayeredPane3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(cat_combo, 0, 139, Short.MAX_VALUE)
                    .addComponent(rate_text)
                    .addComponent(roomno_combo, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(33, 33, 33))
        );
        jLayeredPane3Layout.setVerticalGroup(
            jLayeredPane3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jLayeredPane3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jLayeredPane3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cat_combo, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel26))
                .addGroup(jLayeredPane3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jLayeredPane3Layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addComponent(jLabel27))
                    .addGroup(jLayeredPane3Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(roomno_combo, javax.swing.GroupLayout.DEFAULT_SIZE, 34, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jLayeredPane3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel45)
                    .addComponent(rate_text, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jLayeredPane3.setLayer(jLabel26, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane3.setLayer(cat_combo, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane3.setLayer(jLabel27, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane3.setLayer(jLabel45, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane3.setLayer(rate_text, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane3.setLayer(roomno_combo, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jPanel1.setBackground(new java.awt.Color(0, 102, 102));
        jPanel1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel1.setOpaque(false);

        register_button.setText("Register");
        register_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                register_buttonActionPerformed(evt);
            }
        });

        total_amount.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                total_amountFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                total_amountFocusLost(evt);
            }
        });

        jLabel46.setText("Total Amount");

        invoice_button.setText("Invoice");
        invoice_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                invoice_buttonActionPerformed(evt);
            }
        });

        clear_button.setText("Clear");
        clear_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clear_buttonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(jLabel46)
                .addGap(18, 18, 18)
                .addComponent(total_amount, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(41, 41, 41)
                .addComponent(invoice_button, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(register_button, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(50, 50, 50)
                .addComponent(clear_button, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(25, 25, 25))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel46)
                            .addComponent(total_amount)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(invoice_button, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(register_button, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(clear_button, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap())
        );

        jPanel2.setBackground(new java.awt.Color(0, 102, 102));
        jPanel2.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel2.setOpaque(false);

        jLabel28.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel28.setText("Maternity Patient Registration - Sulaimans Hospital");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel28, javax.swing.GroupLayout.PREFERRED_SIZE, 481, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(513, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel28, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        jButton4.setText("Billing");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jButton1.setText("Home");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton3.setText("Child");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLayeredPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 273, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLayeredPane6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLayeredPane1)
                                    .addComponent(jLayeredPane3))
                                .addGap(18, 18, 18)
                                .addComponent(jLayeredPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 339, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 48, Short.MAX_VALUE)
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jButton4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jButton3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(26, 26, 26))))
                    .addComponent(jScrollPane3))
                .addContainerGap(23, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLayeredPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(jPanel4Layout.createSequentialGroup()
                                        .addComponent(jLayeredPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jLayeredPane3))
                                    .addComponent(jLayeredPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addGap(164, 164, 164)
                                .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jButton4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(29, 29, 29)))
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(25, 25, 25))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLayeredPane6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1373, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, 1363, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 726, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(15, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void register_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_register_buttonActionPerformed
        // TODO add your handling code here:
        registerMaternity();
        ++patientID;
//        resetFields();
    }//GEN-LAST:event_register_buttonActionPerformed

    private void home_contactFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_home_contactFocusLost
        // TODO add your handling code here:
        phone_h = Validation.validatePhone(home_contact, jLabel37, phone_h);
    }//GEN-LAST:event_home_contactFocusLost

    private void nic_textFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_nic_textFocusLost
        // TODO add your handling code here:
        nic = Validation.validateNIC(nic_text, jLabel31, nic);
    }//GEN-LAST:event_nic_textFocusLost

    private void mobile_contactFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_mobile_contactFocusLost
        // TODO add your handling code here:
        phone_m = Validation.validatePhone(mobile_contact, jLabel38, phone_m);
    }//GEN-LAST:event_mobile_contactFocusLost

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        this.dispose();
        Home_Main hm = new Home_Main();
        hm.setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void dob_dcPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_dob_dcPropertyChange
        // TODO add your handling code here:
        dob_text_add.setText(((JTextField)dob_dc.getDateEditor().getUiComponent()).getText());
    }//GEN-LAST:event_dob_dcPropertyChange

    private void duedate_dcPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_duedate_dcPropertyChange
        // TODO add your handling code here:
        duedate_text_add.setText(((JTextField)duedate_dc.getDateEditor().getUiComponent()).getText());
    }//GEN-LAST:event_duedate_dcPropertyChange

    private void search_maternityKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_search_maternityKeyReleased
        // TODO add your handling code here:
        String key = search_maternity.getText();
        while(dm.getRowCount() > 0)
        {
            dm.removeRow(0);
        }
        try{
            String SQL;
            SQL = "SELECT * FROM maternity WHERE patientID LIKE '%"+key+"%' OR NIC LIKE '%"+key+"%' OR fname LIKE '%"+key+"%' OR lname LIKE '%"+key+"%' OR m_contact LIKE '%"+key+"%'";
            PreparedStatement pst;
            pst = conn.prepareStatement(SQL);
            rs = pst.executeQuery();
            while(rs.next())
            {
                //CompanyID = 1+Integer.parseInt(rs.getString(1));
                //Integer.parseInt(jTextField16.getText());
                dm.addRow(new Object[]{rs.getString(1),rs.getString(2),rs.getString(3),rs.getString(4),rs.getString(5),rs.getString(6),
                    rs.getString(7),rs.getString(8),rs.getString(9),rs.getString(11),rs.getString(18)});
            }
        }
        catch(Exception e)
        {
             JOptionPane.showMessageDialog(null,e);
        }
    }//GEN-LAST:event_search_maternityKeyReleased

    private void first_nameFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_first_nameFocusLost
        // TODO add your handling code here:
        String s = first_name.getText();
        letter = Validation.checkLetter(s);
    }//GEN-LAST:event_first_nameFocusLost

    private void last_nameFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_last_nameFocusLost
        // TODO add your handling code here:
        String s = last_name.getText();
        letter = Validation.checkLetter(s);
    }//GEN-LAST:event_last_nameFocusLost

    private void fam_doc_textFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_fam_doc_textFocusLost
        // TODO add your handling code here:
        String s = fam_doc_text.getText();
        letter = Validation.checkLetter(s);
    }//GEN-LAST:event_fam_doc_textFocusLost

    private void rate_textFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_rate_textFocusLost
        // TODO add your handling code here:
        String s = rate_text.getText();
        number = Validation.checkNumber(s);
    }//GEN-LAST:event_rate_textFocusLost

    private void total_amountFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_total_amountFocusLost
        // TODO add your handling code here:
        String s = total_amount.getText();
        number = Validation.checkNumber(s);
    }//GEN-LAST:event_total_amountFocusLost

    private void clear_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clear_buttonActionPerformed
        // TODO add your handling code here:
        resetFields();
    }//GEN-LAST:event_clear_buttonActionPerformed

    private void roomno_comboFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_roomno_comboFocusGained
        // TODO add your handling code here:
        getroomno();
    }//GEN-LAST:event_roomno_comboFocusGained

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        ChildGUI cg = new ChildGUI();
        cg.show();
    }//GEN-LAST:event_jButton3ActionPerformed

    private void dob_text_addFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_dob_text_addFocusLost
        // TODO add your handling code here:
        calcAge();
    }//GEN-LAST:event_dob_text_addFocusLost

    private void nok_nic_textFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_nok_nic_textFocusLost
        // TODO add your handling code here:
        nic = Validation.validateNIC(nok_nic_text, jLabel48, nic);
    }//GEN-LAST:event_nok_nic_textFocusLost

    private void nok_contact_noFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_nok_contact_noFocusLost
        // TODO add your handling code here:
        phone = Validation.validatePhone(nok_contact_no, jLabel49, phone);
    }//GEN-LAST:event_nok_contact_noFocusLost

    private void nok_relationFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_nok_relationFocusLost
        // TODO add your handling code here:
        String s = nok_relation.getText();
        letter = Validation.checkLetter(s);
    }//GEN-LAST:event_nok_relationFocusLost

    private void nok_last_nameFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_nok_last_nameFocusLost
        // TODO add your handling code here:
        String s = nok_last_name.getText();
        letter = Validation.checkLetter(s);
    }//GEN-LAST:event_nok_last_nameFocusLost

    private void nok_first_nameFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_nok_first_nameFocusLost
        // TODO add your handling code here:
        String s = nok_first_name.getText();
        letter = Validation.checkLetter(s);
    }//GEN-LAST:event_nok_first_nameFocusLost

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        BillingGUI bg = new BillingGUI();
        bg.show();
    }//GEN-LAST:event_jButton4ActionPerformed

    private void total_amountFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_total_amountFocusGained
        // TODO add your handling code here:
        getamount();
    }//GEN-LAST:event_total_amountFocusGained

    private void invoice_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_invoice_buttonActionPerformed
         try{
           String report="C:\\Users\\Haran\\Documents\\NetBeansProjects\\ps_Atlanta\\src\\maternity_report\\report_maternity.jrxml";
           JasperReport jasp=JasperCompileManager.compileReport(report);
           JasperPrint jas_print=JasperFillManager.fillReport(jasp,null,conn);
           JasperViewer.viewReport(jas_print);
       }
       catch(Exception e){
          JOptionPane.showMessageDialog(null, e);
       }
    }//GEN-LAST:event_invoice_buttonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MaternityGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MaternityGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MaternityGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MaternityGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MaternityGUI().setVisible(true);
            }
        });
    }
    
    public void registerMaternity(){

    String title = title_combo.getSelectedItem().toString();
    String fname = first_name.getText();
    String lname = last_name.getText();
    //Format formatter = new SimpleDateFormat("dd-MM-yyyy");
    String dob = dob_text_add.getText();
    String age = age_text.getText();
    String NIC = nic_text.getText();
    String perm_add = perm_add_text.getText();
    String mar_status = mar_stat.getSelectedItem().toString();
    String res_add = res_add_text.getText();
    String h_contact = home_contact.getText();
    String m_contact = mobile_contact.getText();
    String duedate = duedate_text_add.getText();
    String fam_doctor = fam_doc_text.getText();
    String mat_doctor = mat_doc_combo.getSelectedItem().toString();
    String pediat = pediat_combo.getSelectedItem().toString();
    String room_cat = cat_combo.getSelectedItem().toString();
    String room_rate = rate_text.getText();
    String room_no = roomno_combo.getSelectedItem().toString();
    String nok_title = nok_title_com.getSelectedItem().toString();
    String nok_fname = nok_first_name.getText();
    String nok_lname = nok_last_name.getText();
    String nok_nic = nok_nic_text.getText();
    String nok_relat = nok_relation.getText();
    String nok_add = nok_add_text.getText();
    String nok_contact = nok_contact_no.getText();
    String tot_amount = total_amount.getText();
    
    if (title.equals("") || fname.trim().equals("") || lname.trim().equals("")
            || dob.trim().equals("") || age.trim().equals("") || nic == false || perm_add.trim().equals("") 
            || mar_status.trim().equals("") || res_add.trim().equals("") || phone_h == false || phone_m == false 
            || duedate.trim().equals("") || fam_doctor.trim().equals("") || mat_doctor.trim().equals("")
            || pediat.trim().equals("") || room_cat.trim().equals("") || room_rate.trim().equals("") || room_no.trim().equals("") 
            || nok_title.trim().equals("") || nok_fname.trim().equals("") || nok_lname.trim().equals("") 
            || nok_nic.trim().equals("") || nok_relat.trim().equals("") || nok_add.trim().equals("") || phone == false || tot_amount.trim().equals("")) 
    {
            JOptionPane.showMessageDialog(null,"Fill All the Fields");
    }
    else {
            try {
            pst = conn.prepareStatement("Insert into maternity values(?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)");
            pst.setInt(1, patientID);
            pst.setString(2,String.valueOf(title));
            pst.setString(3,fname);
            pst.setString(4,lname);
            pst.setString(5,dob);
            pst.setString(6,age);
            pst.setString(7,NIC);
            pst.setString(8,perm_add);
            pst.setString(9,String.valueOf(mar_status));
            pst.setString(10,res_add);
            pst.setString(11,h_contact);
            pst.setString(12,m_contact);
            pst.setString(13,duedate);
            pst.setString(14,String.valueOf(fam_doctor));
            pst.setString(15,String.valueOf(mat_doctor));
            pst.setString(16,pediat);
            pst.setString(17,String.valueOf(room_cat));
            pst.setString(18,room_no);
            pst.setString(19,room_rate);
            pst.setString(20,String.valueOf(nok_title));
            pst.setString(21,nok_fname);
            pst.setString(22,nok_lname);
            pst.setString(23,nok_nic);
            pst.setString(24,nok_relat);
            pst.setString(25,nok_add);
            pst.setString(26,nok_contact);
            pst.setString(27,tot_amount);
            
            
            pst.executeUpdate();
            JOptionPane.showMessageDialog(null,"Inserted Successfully");
            
           dm.addRow(new Object[]{patientID,String.valueOf(title),fname,lname,dob,age,NIC,perm_add,h_contact,room_no});
           ++patientID;
                
            } catch (SQLException ex) {
                Logger.getLogger(opdGUI.class.getName()).log(Level.SEVERE, null, ex);
            } 
        } 
    }
    
    private void resetFields() {
        last_name.setText(null);
        mobile_contact.setText(null);
        fam_doc_text.setText(null);
        nok_first_name.setText(null);
        nok_last_name.setText(null);
        search_maternity.setText(null);
        nok_relation.setText(null);
        first_name.setText(null);
        age_text.setText(null);
        home_contact.setText(null);
        nok_contact_no.setText(null);
        nic_text.setText(null);
        rate_text.setText(null);
        total_amount.setText(null);
        nok_nic_text.setText(null);
        
        res_add_text.setText(null);
        perm_add_text.setText(null);
        nok_add_text.setText(null);

        title_combo.setSelectedItem("select");
        roomno_combo.setSelectedItem("select");
        mar_stat.setSelectedItem("select");
        mat_doc_combo.setSelectedItem("select");
        pediat_combo.setSelectedItem("select");
        nok_title_com.setSelectedItem("select");
        cat_combo.setSelectedItem("select");

        dob_dc.setDate(null);
        duedate_dc.setDate(null);
        
    }
    
    public void calcAge(){
        
        String dobcal = dob_text_add.getText();
        
        String[] dateParts = dobcal.split("-");
        String year = dateParts[0];
        
        int y = Integer.parseInt(year);
        
        int age = (2016 - y);
        age_text.setText(String.valueOf(age));
        
//        try{
//        
//            DateFormat dateFormat = new SimpleDateFormat("yyyy/MM/dd HH:mm:ss");
//            String date = new Date().toString();
//            String[] dateParts = date.split("/");
//            String year = dateParts[0];
//            String month = dateParts[1];
//            String day = dateParts[2];
//            
//            int y = Integer.parseInt(year);
//            int m = Integer.parseInt(month);
//            int d = Integer.parseInt(day);
//            
//            String dob = ((JTextField)dob_dc.getDateEditor().getUiComponent()).getText();
//            String[] parts1 = dob.split("-");
//            String dob_year = parts1[0];
//            String dob_month = parts1[1];
//            String dob_day = parts1[2];
//            
//            int dob_y=Integer.parseInt(dob_year);
//            int dob_m=Integer.parseInt(dob_month);
//            int dob_d=Integer.parseInt(dob_day);
////        
////            LocalDate birthdate = LocalDate.of(dob_y, dob_m, dob_d);
////            LocalDate now = LocalDate.of(y, m, d);
////            long age = ChronoUnit.YEARS.between(birthdate, now);
//            int age = (y - dob_y);
//            age_text.setText(String.valueOf(age));
//        }
//        catch(Exception e){
//        
//        }
    }
    
    public void getroomno(){
    
        try {
            String fc = cat_combo.getSelectedItem().toString();
            String SQL;
            if (fc.equals("Luxury")){
                SQL = "select roomNo,roomCharge from room WHERE roomCategory = 'Maternity Ward' AND roomType = 'Lx' AND roomAvailabilityStatus = 1";
            } else if (fc.equals("Semi-Luxury")){
                SQL = "select roomNo,roomCharge from room WHERE roomCategory = 'Maternity Ward' AND roomType = 'SLx' AND roomAvailabilityStatus = 1";
            } else {
                SQL = "select roomNo,roomCharge from room WHERE roomCategory = 'Maternity Ward' AND roomType = 'Std' AND roomAvailabilityStatus = 1";
            }
            pst = conn.prepareStatement(SQL);
            rs1 = pst.executeQuery();
            while(rs1.next()) {
                roomno_combo.addItem(rs1.getString(1));
                rate_text.setText(rs1.getString(2));

                }
        } catch (SQLException ex) {
            Logger.getLogger(opdGUI.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    
    public void getamount() {
        String room_rate = rate_text.getText();
        String mat_doctor = mat_doc_combo.getSelectedItem().toString();
        String pediat = pediat_combo.getSelectedItem().toString();
        
        try {
        
        double docfee1 = 0;
        double docfee2 = 0;
        double total = 0;
        String SQL1 = "select fee from physicians where lname like '"+mat_doctor+"'";
        pst = conn.prepareStatement(SQL1);
        rs = pst.executeQuery();
        while(rs.next()) {
            docfee1 = Double.parseDouble(rs.getString(1));
            }
        
        String SQL2 = "select fee from physicians where lname like '"+pediat+"'";
        pst = conn.prepareStatement(SQL2);
        rs = pst.executeQuery();
        while(rs.next()) {
            docfee2 = Double.parseDouble(rs.getString(1));
            }
        
        double amt = Double.parseDouble(room_rate);
        total = docfee1+docfee2+amt;
        total_amount.setText(String.valueOf(total));
        
        }catch (SQLException ex) {
            Logger.getLogger(opdGUI.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    
    public void maternity() {
    while(dm.getRowCount() > 0)
    {
        dm.removeRow(0);
    }
    try {
        String SQL;
        SQL = "SELECT * FROM maternity";
        PreparedStatement pst = conn.prepareStatement(SQL);
        rs = pst.executeQuery();
        while(rs.next())
        {
            patientID = 1+Integer.parseInt(rs.getString(1));
            dm.addRow(new Object[]{rs.getString(1),rs.getString(2),rs.getString(3),rs.getString(4),rs.getString(5),rs.getString(6),
                rs.getString(7),rs.getString(8),rs.getString(12),rs.getString(18)});
        }
    } catch(SQLException | NumberFormatException e) {
            JOptionPane.showMessageDialog(null,e);
    }
}

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable TableMat;
    private javax.swing.JTextField age_text;
    private javax.swing.JComboBox<String> cat_combo;
    private javax.swing.JButton clear_button;
    private com.toedter.calendar.JDateChooser dob_dc;
    private javax.swing.JTextField dob_text_add;
    private com.toedter.calendar.JDateChooser duedate_dc;
    private javax.swing.JTextField duedate_text_add;
    private javax.swing.JTextField fam_doc_text;
    private javax.swing.JTextField first_name;
    private javax.swing.JTextField home_contact;
    private javax.swing.JButton invoice_button;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel45;
    private javax.swing.JLabel jLabel46;
    private javax.swing.JLabel jLabel48;
    private javax.swing.JLabel jLabel49;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLayeredPane jLayeredPane1;
    private javax.swing.JLayeredPane jLayeredPane2;
    private javax.swing.JLayeredPane jLayeredPane3;
    private javax.swing.JLayeredPane jLayeredPane5;
    private javax.swing.JLayeredPane jLayeredPane6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTextField last_name;
    private javax.swing.JComboBox<String> mar_stat;
    private javax.swing.JComboBox<String> mat_doc_combo;
    private javax.swing.JLabel maternity_ID;
    private javax.swing.JTextField mobile_contact;
    private javax.swing.JTextField nic_text;
    private javax.swing.JTextArea nok_add_text;
    private javax.swing.JTextField nok_contact_no;
    private javax.swing.JTextField nok_first_name;
    private javax.swing.JTextField nok_last_name;
    private javax.swing.JTextField nok_nic_text;
    private javax.swing.JTextField nok_relation;
    private javax.swing.JComboBox<String> nok_title_com;
    private javax.swing.JComboBox<String> pediat_combo;
    private javax.swing.JTextArea perm_add_text;
    private javax.swing.JTextField rate_text;
    private javax.swing.JButton register_button;
    private javax.swing.JTextArea res_add_text;
    private javax.swing.JComboBox<String> roomno_combo;
    private javax.swing.JTextField search_maternity;
    private javax.swing.JComboBox<String> title_combo;
    private javax.swing.JTextField total_amount;
    // End of variables declaration//GEN-END:variables

}
